# Generated by Django 4.2.7 on 2023-11-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='movie',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='rating',
        ),
    ]
